### ISSUE TITLE
Failų struktūra

### ISSUE THREAD

**Issue by ZilvinasJonaitis** [vilisas/trafikas#1]
Dabar radijo konferencijų failai saugomi šakniniame kataloge. Laikui bėgant failų daugės ir README.md  tekstas slinksis žemyn kol galiausiai visai pasislėps. Mano nuomone, README.md tekstas turi visuomet matytis atsidarius Github kompiuteryje arba telefone. Todėl mano pasiūlymas yra grupuoti failus aplankuose pagal metus, pvz. 2023 m., 2024 m. taip toliau. Tikimybė, kad metų aplankai paslinks README.md taip žemai, kad jo nebesimatys yra minimali - radijo konferencija, kaip informacijos sklaidos šaltinis, greičiausiai išnyks daug ankščiau ;)

**Comment by vilisas** [comment]
@ZilvinasJonaitis Pasinaudojau idėja, grupuosiu pagal metus :-)
